import "~/styles/globals.css";

import { Oswald } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { type ReactNode } from "react";
import { Analytics } from "@vercel/analytics/react";
import { Layout } from "~/app/_components/Navigation/Layout";
import { MinVersion } from "~/app/_components/MinVersion";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "WorkoutTrack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/assets/icon/icon.png"></link>
          <meta name="theme-color" content="#fff" />
          <title>WorkoutTrack</title>
        </head>
        <body className={`font-sans ${oswald.variable}`}>
          <TRPCReactProvider cookies={cookies().toString()}>
            <Layout>{children}</Layout>
            <MinVersion />
            <Analytics />
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
