import { Units } from './Units';

export interface Food {
    id: number;
    name: string;
    brand: string;
    servingSize: number;
    servingSizeUnit: Units;
    calories: number;
    totalFat?: number;
    saturatedFat?: number;
    transFat?: number;
    monounsaturatedFat?: number;
    polyunsaturatedFat?: number;
    carbohydrates?: number;
    fiber?: number;
    sugar?: number;
    protein?: number;
    cholesterol?: number;
    sodium?: number;
    potassium?: number;
    calcium?: number;
    iron: number;
    magnesium: number;
    zinc: number;
    phosphorus: number;
    vitaminA: number;
    vitaminC: number;
    vitaminD?: number;
    vitaminE?: number;
    vitaminK?: number;
    thiamin?: number;
    riboflavin?: number;
    niacin?: number;
    vitaminB6?: number;
    folate?: number;
    vitaminB12?: number;
    water?: number;
    alcohol?: number;
    caffeine?: number;
}
