require_relative '../../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBarcodeScanner', :path => '../../../../node_modules/.pnpm/@capacitor-community+barcode-scanner@4.0.1_@capacitor+core@5.5.1/node_modules/@capacitor-community/barcode-scanner'
  pod 'CapacitorFirebaseApp', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+app@5.2.0_@capacitor+core@5.5.1_firebase@10.5.2/node_modules/@capacitor-firebase/app'
  pod 'CapacitorFirebaseAuthentication', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+authentication@5.2.0_@capacitor+core@5.5.1_firebase@10.5.2/node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorApp', :path => '../../../../node_modules/.pnpm/@capacitor+app@5.0.6_@capacitor+core@5.5.1/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../../node_modules/.pnpm/@capacitor+camera@5.0.7_@capacitor+core@5.5.1/node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/.pnpm/@capacitor+filesystem@5.1.4_@capacitor+core@5.5.1/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/.pnpm/@capacitor+haptics@5.0.6_@capacitor+core@5.5.1/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.pnpm/@capacitor+keyboard@5.0.6_@capacitor+core@5.5.1/node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.pnpm/@capacitor+status-bar@5.0.6_@capacitor+core@5.5.1/node_modules/@capacitor/status-bar'
  pod 'CapacitorIosAutofillSavePassword', :path => '../../../../node_modules/.pnpm/capacitor-ios-autofill-save-password@1.1.5_@capacitor+core@5.5.1/node_modules/capacitor-ios-autofill-save-password'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
                  target.build_configurations.each do |config|
                      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                  end
              end
          end
      end
end
